var buildInBank = {  
  "_id":"1536591973331_bank",
  "label":"Band",
  "date":"2018-09-10",
  "presets":[  
     {  
        "_id":"1536591988742_preset",
        "label":"retroCrunch",
        "date":"2018-09-10",
        "plugs":[  
           {  
              "id":"p_1536591911534",
              "type":"pedal-minilogue",
              "position":{  
                 "x":196,
                 "y":82.88423988842399
              },
              "settings":{  
                 "egint":3500,
                 "voicedepth":0,
                 "ringmodulation":0,
                 "noise":0.1,
                 "osc2Octave":3,
                 "osc1Octave":3,
                 "egrelease":1,
                 "egsustain":0.5,
                 "egdecay":1,
                 "egattack":0.5,
                 "amprelease":0.001,
                 "ampsustain":0.5,
                 "ampdecay":1,
                 "ampattack":0.001,
                 "osc2shape":0.5,
                 "osc1shape":0.5,
                 "osc2gain":8,
                 "osc1gain":8,
                 "pitch2":1,
                 "pitch1":1,
                 "mix":0.5,
                 "time":0.5,
                 "feedback":0.5,
                 "highpass":30,
                 "lowpass":2000,
                 "resonance":0.1,
                 "mastergain":5,
                 "lforate":0,
                 "lfoint":20,
                 "wave1":"sawtooth",
                 "status":"disable",
                 "wave2":"sawtooth",
                 "lfodest":"cutoff",
                 "mode":"poly"
              }
           },
           {  
              "id":"p_1536591921724",
              "type":"pedal-zitarev2",
              "position":{  
                 "x":885,
                 "y":153.7852161785216
              },
              "settings":{  
                 "/zitaRev/Zita_Rev1/Input/In_Delay":"80",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/LF_X":"800",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/Low_RT60":"6",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/Mid_RT60":"6",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/HF_Damping":"18000",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_1/Eq1_Freq":"2000",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_1/Eq1_Level":"13",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_2/Eq2_Freq":"8000",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_2/Eq2_Level":"14",
                 "/zitaRev/Zita_Rev1/Output/Dry/Wet_Mix":"0.699999988079071",
                 "/zitaRev/Zita_Rev1/Output/Level":"0",
                 "/zitaRev/bypass":"0"
              }
           },
           {  
              "id":"p_1536591940050",
              "type":"pedal-cleanmachine",
              "position":{  
                 "x":452,
                 "y":441
              },
              "settings":{  
                 "CG":"6.7",
                 "EQ":[  
                    -2,
                    10,
                    -10,
                    -20,
                    17,
                    3
                 ],
                 "Q4":"0.0",
                 "Q3":"0.0",
                 "Q2":"0.0",
                 "Q1":"0.0",
                 "F4":5696,
                 "F3":2382,
                 "F2":569,
                 "F1":147,
                 "HCF":12000,
                 "LCF":256,
                 "presence":"8.0",
                 "reverb":"2.0",
                 "treble":"5.0",
                 "middle":"5.0",
                 "bass":"5.0",
                 "drive":"0.0",
                 "master":"6.5",
                 "volume":"5.9",
                 "status":"enable",
                 "preset":"9"
              }
           },
           {  
              "id":"p_1536591947010",
              "type":"pedal-mixer",
              "position":{  
                 "x":1528.75,
                 "y":392.5
              },
              "settings":{  
                 "nbcanaux":2,
                 "gain":0.5
              }
           }
        ],
        "connexions":[  
           {  
              "in":{  
                 "id":"p_1536591947010",
                 "inputnumber":1
              },
              "out":"p_1536591940050"
           },
           {  
              "in":{  
                 "id":"pedalOut",
                 "inputnumber":0
              },
              "out":"p_1536591947010"
           },
           {  
              "in":{  
                 "id":"p_1536591947010",
                 "inputnumber":0
              },
              "out":"p_1536591921724"
           },
           {  
              "in":{  
                 "id":"p_1536591921724",
                 "inputnumber":0
              },
              "out":"p_1536591911534"
           },
           {  
              "in":{  
                 "id":"p_1536591940050",
                 "inputnumber":0
              },
              "out":"pedalIn1"
           }
        ]
     },
     {  
        "_id":"1536592071936_preset",
        "label":"WHActiv",
        "date":"2018-09-10",
        "plugs":[  
           {  
              "id":"p_1536592006885",
              "type":"pedal-pingpongdelay",
              "position":{  
                 "x":247,
                 "y":345
              },
              "settings":{  
                 "mix":0.5,
                 "time":0.5,
                 "feedback":0.5,
                 "status":"enable"
              }
           },
           {  
              "id":"p_1536592011927",
              "type":"pedal-mixer",
              "position":{  
                 "x":1381,
                 "y":260
              },
              "settings":{  
                 "nbcanaux":2,
                 "gain":0.5
              }
           },
           {  
              "id":"p_1536592019492",
              "type":"pedal-wahvox",
              "position":{  
                 "x":517,
                 "y":392
              },
              "settings":{  
                 "qfactor":3,
                 "frequency":3,
                 "mode":1,
                 "effect":50,
                 "status":"enable",
                 "boost":"disable",
                 "qMin":2,
                 "qMax":7,
                 "freqMin":450,
                 "freqMax":1600
              }
           },
           {  
              "id":"p_1536592040847",
              "type":"pedal-cleanmachine",
              "position":{  
                 "x":622,
                 "y":147
              },
              "settings":{  
                 "CG":"5.4",
                 "EQ":[  
                    -2,
                    -1,
                    2,
                    2,
                    -7,
                    -13
                 ],
                 "Q4":11,
                 "Q3":42,
                 "Q2":49,
                 "Q1":0,
                 "F4":4680,
                 "F3":1915,
                 "F2":569,
                 "F1":147,
                 "HCF":7000,
                 "LCF":90,
                 "presence":5,
                 "reverb":"2.0",
                 "treble":5,
                 "middle":5,
                 "bass":5,
                 "drive":"10.0",
                 "master":"0.7",
                 "volume":7.9,
                 "status":"enable",
                 "preset":"4"
              }
           },
           {  
              "id":"p_1536592045696",
              "type":"pedal-distomachine",
              "position":{  
                 "x":830,
                 "y":466
              },
              "settings":{  
                 "CG":"9.2",
                 "EQ":[  
                    19,
                    8,
                    -6,
                    -10,
                    7,
                    2
                 ],
                 "gain2":1,
                 "LS3Gain":-6,
                 "LS3Freq":720,
                 "HP1Q":0.707099974155426,
                 "HP1Freq":6,
                 "gain1":1,
                 "LS2Gain":-10.199999809265137,
                 "LS2Freq":320,
                 "LS1Gain":-6,
                 "LS1Freq":720,
                 "presence":"9.4",
                 "reverb":"0.7",
                 "treble":"3.8",
                 "middle":"8.0",
                 "bass":"8.7",
                 "drive":"5.2",
                 "master":"5.5",
                 "volume":"2",
                 "status":"enable",
                 "preset":"5"
              }
           }
        ],
        "connexions":[  
           {  
              "in":{  
                 "id":"p_1536592006885",
                 "inputnumber":0
              },
              "out":"pedalIn1"
           },
           {  
              "in":{  
                 "id":"p_1536592019492",
                 "inputnumber":0
              },
              "out":"p_1536592006885"
           },
           {  
              "in":{  
                 "id":"p_1536592040847",
                 "inputnumber":0
              },
              "out":"p_1536592006885"
           },
           {  
              "in":{  
                 "id":"p_1536592045696",
                 "inputnumber":0
              },
              "out":"p_1536592019492"
           },
           {  
              "in":{  
                 "id":"p_1536592011927",
                 "inputnumber":1
              },
              "out":"p_1536592045696"
           },
           {  
              "in":{  
                 "id":"p_1536592011927",
                 "inputnumber":0
              },
              "out":"p_1536592040847"
           },
           {  
              "in":{  
                 "id":"pedalOut",
                 "inputnumber":0
              },
              "out":"p_1536592011927"
           }
        ]
     },
     {  
        "_id":"1536592149499_preset",
        "label":"progressivduo",
        "date":"2018-09-10",
        "plugs":[  
           {  
              "id":"p_1536592087441",
              "type":"pedal-cleanmachine",
              "position":{  
                 "x":1152,
                 "y":144
              },
              "settings":{  
                 "CG":"5.4",
                 "EQ":[  
                    -2,
                    -1,
                    2,
                    2,
                    -7,
                    -13
                 ],
                 "Q4":11,
                 "Q3":42,
                 "Q2":49,
                 "Q1":0,
                 "F4":4680,
                 "F3":1915,
                 "F2":569,
                 "F1":147,
                 "HCF":7000,
                 "LCF":90,
                 "presence":5,
                 "reverb":"2.0",
                 "treble":5,
                 "middle":5,
                 "bass":5,
                 "drive":"10.0",
                 "master":"0.7",
                 "volume":7.9,
                 "status":"disable",
                 "preset":"4"
              }
           },
           {  
              "id":"p_1536592088607",
              "type":"pedal-distomachine",
              "position":{  
                 "x":663,
                 "y":422
              },
              "settings":{  
                 "CG":"8.8",
                 "EQ":[  
                    10,
                    5,
                    -7,
                    -7,
                    16,
                    0
                 ],
                 "gain2":1,
                 "LS3Gain":-6,
                 "LS3Freq":720,
                 "HP1Q":0.707099974155426,
                 "HP1Freq":6,
                 "gain1":1,
                 "LS2Gain":1.600000023841858,
                 "LS2Freq":320,
                 "LS1Gain":-6,
                 "LS1Freq":720,
                 "presence":"6.9",
                 "reverb":"1.4",
                 "treble":"3.2",
                 "middle":"4.7",
                 "bass":"6.7",
                 "drive":"7.8",
                 "master":"7.2",
                 "volume":"3.0",
                 "status":"disable",
                 "preset":"6"
              }
           },
           {  
              "id":"p_1536592098583",
              "type":"pedal-zitarev2",
              "position":{  
                 "x":1374,
                 "y":377
              },
              "settings":{  
                 "/zitaRev/Zita_Rev1/Input/In_Delay":"60",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/LF_X":"200",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/Low_RT60":"3",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/Mid_RT60":"2",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/HF_Damping":"6000",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_1/Eq1_Freq":"315",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_1/Eq1_Level":"0",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_2/Eq2_Freq":"1500",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_2/Eq2_Level":"0",
                 "/zitaRev/Zita_Rev1/Output/Dry/Wet_Mix":"0",
                 "/zitaRev/Zita_Rev1/Output/Level":"0",
                 "/zitaRev/bypass":"1"
              }
           },
           {  
              "id":"p_1536592110917",
              "type":"pedal-wahvox",
              "position":{  
                 "x":202,
                 "y":220
              },
              "settings":{  
                 "qfactor":3,
                 "frequency":3,
                 "mode":1,
                 "effect":50,
                 "status":"disable",
                 "boost":"disable",
                 "qMin":2,
                 "qMax":7,
                 "freqMin":450,
                 "freqMax":1600
              }
           },
           {  
              "id":"p_1536592124110",
              "type":"pedal-stereoflanger",
              "position":{  
                 "x":856,
                 "y":174
              },
              "settings":{  
                 "feedback":0.5,
                 "delay":0.003,
                 "depth":0.005,
                 "frequency":0.15,
                 "status":"disable"
              }
           }
        ],
        "connexions":[  
           {  
              "in":{  
                 "id":"p_1536592088607",
                 "inputnumber":0
              },
              "out":"pedalIn1"
           },
           {  
              "in":{  
                 "id":"p_1536592098583",
                 "inputnumber":0
              },
              "out":"p_1536592088607"
           },
           {  
              "in":{  
                 "id":"pedalOut",
                 "inputnumber":0
              },
              "out":"p_1536592098583"
           },
           {  
              "in":{  
                 "id":"p_1536592110917",
                 "inputnumber":0
              },
              "out":"pedalIn2"
           },
           {  
              "in":{  
                 "id":"p_1536592124110",
                 "inputnumber":0
              },
              "out":"p_1536592110917"
           },
           {  
              "in":{  
                 "id":"p_1536592087441",
                 "inputnumber":0
              },
              "out":"p_1536592124110"
           },
           {  
              "in":{  
                 "id":"pedalOut",
                 "inputnumber":0
              },
              "out":"p_1536592087441"
           }
        ]
     },
     {  
        "_id":"1536592213467_preset",
        "label":"mmmm",
        "date":"2018-09-10",
        "plugs":[  
           {  
              "id":"p_1536592157486",
              "type":"pedal-minilogue",
              "position":{  
                 "x":112,
                 "y":87
              },
              "settings":{  
                 "egint":3500,
                 "voicedepth":0,
                 "ringmodulation":0,
                 "noise":0.1,
                 "osc2Octave":3,
                 "osc1Octave":3,
                 "egrelease":1,
                 "egsustain":0.5,
                 "egdecay":1,
                 "egattack":0.5,
                 "amprelease":0.001,
                 "ampsustain":0.5,
                 "ampdecay":1,
                 "ampattack":0.001,
                 "osc2shape":0.5,
                 "osc1shape":0.5,
                 "osc2gain":8,
                 "osc1gain":8,
                 "pitch2":1,
                 "pitch1":1,
                 "mix":0.5,
                 "time":0.5,
                 "feedback":0.5,
                 "highpass":30,
                 "lowpass":2000,
                 "resonance":0.1,
                 "mastergain":5,
                 "lforate":0,
                 "lfoint":20,
                 "wave1":"sawtooth",
                 "status":"disable",
                 "wave2":"square",
                 "lfodest":"cutoff",
                 "mode":"poly"
              }
           },
           {  
              "id":"p_1536592163934",
              "type":"pedal-zitarev2",
              "position":{  
                 "x":855,
                 "y":198
              },
              "settings":{  
                 "/zitaRev/Zita_Rev1/Input/In_Delay":"80",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/LF_X":"800",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/Low_RT60":"6",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/Mid_RT60":"6",
                 "/zitaRev/Zita_Rev1/Decay_Times_in_Bands_(see_tooltips)/HF_Damping":"18000",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_1/Eq1_Freq":"2000",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_1/Eq1_Level":"13",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_2/Eq2_Freq":"8000",
                 "/zitaRev/Zita_Rev1/RM_Peaking_Equalizer_2/Eq2_Level":"14",
                 "/zitaRev/Zita_Rev1/Output/Dry/Wet_Mix":"0.699999988079071",
                 "/zitaRev/Zita_Rev1/Output/Level":"0",
                 "/zitaRev/bypass":"0"
              }
           },
           {  
              "id":"p_1536592173245",
              "type":"pedal-wahvox",
              "position":{  
                 "x":324,
                 "y":425
              },
              "settings":{  
                 "qfactor":3,
                 "frequency":3,
                 "mode":1,
                 "effect":50,
                 "status":"enable",
                 "boost":"disable",
                 "qMin":2,
                 "qMax":7,
                 "freqMin":450,
                 "freqMax":1600
              }
           },
           {  
              "id":"p_1536592177256",
              "type":"pedal-distomachine",
              "position":{  
                 "x":902.5,
                 "y":502.5
              },
              "settings":{  
                 "CG":"1.5",
                 "EQ":[  
                    19,
                    8,
                    -6,
                    -10,
                    7,
                    2
                 ],
                 "gain2":1,
                 "LS3Gain":-6,
                 "LS3Freq":720,
                 "HP1Q":0.707099974155426,
                 "HP1Freq":6,
                 "gain1":1,
                 "LS2Gain":-10.199999809265137,
                 "LS2Freq":320,
                 "LS1Gain":-6,
                 "LS1Freq":720,
                 "presence":"9.4",
                 "reverb":"0.7",
                 "treble":"3.8",
                 "middle":"7.6",
                 "bass":"8.7",
                 "drive":"8",
                 "master":"2.8",
                 "volume":"1.8",
                 "status":"enable",
                 "preset":"3"
              }
           }
        ],
        "connexions":[  
           {  
              "in":{  
                 "id":"p_1536592163934",
                 "inputnumber":0
              },
              "out":"p_1536592157486"
           },
           {  
              "in":{  
                 "id":"pedalOut",
                 "inputnumber":0
              },
              "out":"p_1536592163934"
           },
           {  
              "in":{  
                 "id":"p_1536592177256",
                 "inputnumber":0
              },
              "out":"p_1536592173245"
           },
           {  
              "in":{  
                 "id":"p_1536592173245",
                 "inputnumber":0
              },
              "out":"pedalIn1"
           },
           {  
              "in":{  
                 "id":"pedalOut",
                 "inputnumber":0
              },
              "out":"p_1536592177256"
           }
        ]
     }
  ]
}